spring:
   h2:
     console:
       enabled: true
       path: /h2
   datasource:
      url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password:
      driver-class-name:  org.h2.Driver

   jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          use_sql_comments: true
          default_batch_fetch_size : 100

logging:
   level:
     org.hibernate.SQL:  debug